resources:
  - name: self_repo
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: Ranjansingh41/pipelines_run_1
      branches:
        include: ^tests-failing$  
      
pipelines:
  - name: Pipeline
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
          # integrations:
          #   - name: gen
          inputResources:
            - name: self_repo
        execution: 
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests/empty/temp
            - save_tests saveTests/failing
            - add_pipeline_files saveTests/failing pipelines_state
            - add_run_files saveTests/failing run_state
            - echo "Passed"
            - popd
