pipelines:
  - name: pipeline_language 
    steps:
      - name: matrix_2
        type: Matrix
        stepMode: Bash
        configuration:
          timeoutSeconds: 3600
        matrix:
          environmentVariables:
            - env1: one
              env2: two
              env3: three
            - env1: changed1
              env2: changed2
            - key_1: value1
              key_2: value2
          runtimes:
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 13
        execution:
          onExecute:
            - echo "I am on matrix step"
    #         - ls -l ./Matrix_Fan_Out_1
    #         - 'touch ${steplet_id}_file'
    #         - 'echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file'
    #         - >-
    #           echo "Envs env1 = $env1 , env2 = $env2 , env3 = $env3" >>
    #           ${steplet_id}_file
    #         - >-
    #           echo "Runtime image name - $step_image_name, Runtime image tag -
    #           $step_image_tag
    
