resources:
  - name: test_bash1
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: Ranjansingh41/sample_test 
      
pipelines:
  - name: dynamic_node_test
    steps:
      - name: Test_pipelines
        type: Matrix
        stepMode: Bash
        configuration:
          nodePool: u18dynamic
          inputResources: # optional
            - name: test_bash1  #u16dynamic
        stepletMultipliers:
          environmentVariables:
            - env1: one
              env2: two 
        execution:
          onExecute:
            - echo "I am on matrix step"
            
      - name: Matrix_Fan_Out_2
        type: PreMatrix
        configuration:
          nodePool: u18dynamic
          inputSteps:
            - name: Test_pipelines
          inputResources:
            - name: test_bash1
        execution:
          onExecute:
            - echo "I am on matrix step"
            
